# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [11]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1, 2, 4])

# Create a 2-dimensional NumPy array using np.array()

a2 = np.array([[12, 43, 43],
              [23, 34, 45]])
# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[12, 34, 44],
              [34, 54, 56],
              [344, 56, 2]],
             [[12, 34, 34],
             [23, 21, 12],
             [23, 4, 66]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [15]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [16]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, type(a2)

((2, 3), 2, dtype('int32'), numpy.ndarray)

In [17]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.dtype, type(a3)

((2, 3, 3), 3, dtype('int32'), numpy.ndarray)

In [19]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(a2)
df

0   1   2
0  12  43  43
1  23  34  45

In [22]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [27]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [29]:
# Create an array within a range of 0 and 100 with step 3
a4 = np.arange(0, 100, 3)
a4

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [45]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
a5 = np.random.randint(10, size=(7,2))
a5

array([[1, 2],
       [7, 7],
       [0, 1],
       [7, 9],
       [0, 8],
       [4, 1],
       [5, 3]])

In [43]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
a6 = np.random.random((3,5))
a6

array([[0.4895843 , 0.61864897, 0.43152723, 0.55051819, 0.78467178],
       [0.09159655, 0.72409536, 0.46860301, 0.71246125, 0.39307577],
       [0.27733177, 0.37667268, 0.12133233, 0.55501025, 0.17826554]])

In [50]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
a7 = np.random.randint(10, size=(4, 6))
a7

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [52]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
a8 = np.random.randint(1, 10, size=(3, 7)) 

# Find the unique numbers in the array you just created
np.unique(a8)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [54]:
# Find the 0'th index of the latest array you created
a8[0]

array([5, 2, 4, 7, 8, 3, 1])

In [63]:
# Get the first 2 rows of latest array you created
a8[:2]

array([[5, 2, 4, 7, 8, 3, 1],
       [4, 2, 8, 4, 2, 6, 6]])

In [66]:
# Get the first 2 values of the first 2 rows of the latest array
a8[:2,:2]

array([[5, 2],
       [4, 2]])

In [69]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
a9 = np.random.randint(10, size=(3, 5))
a10 = np.zeros((3, 5))

In [76]:
# Add the two arrays together
a11 = a9 + a10
a11

array([[7., 7., 2., 0., 7.],
       [2., 2., 0., 4., 9.],
       [6., 9., 8., 6., 8.]])

In [77]:
# Create another array of ones of shape (5, 3)
a12 = np.ones((5,3))
a12

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [86]:
# Try add the array of ones and the other most recent array together
a13 = a11 + a12.T
a13

array([[ 8.,  8.,  3.,  1.,  8.],
       [ 3.,  3.,  1.,  5., 10.],
       [ 7., 10.,  9.,  7.,  9.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [87]:
# Create another array of ones of shape (3, 5)
a14 = np.ones((3, 5))
a14

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [89]:
# Subtract the new array of ones from the other most recent array
a15 = a13 - a12.T
a15

array([[7., 7., 2., 0., 7.],
       [2., 2., 0., 4., 9.],
       [6., 9., 8., 6., 8.]])

In [96]:
# Multiply the ones array with the latest array
a16 = a14 * a15
a16

array([[7., 7., 2., 0., 7.],
       [2., 2., 0., 4., 9.],
       [6., 9., 8., 6., 8.]])

In [97]:
# Take the latest array to the power of 2 using '**'
a17 = a16 ** 2
a17

array([[49., 49.,  4.,  0., 49.],
       [ 4.,  4.,  0., 16., 81.],
       [36., 81., 64., 36., 64.]])

In [99]:
# Do the same thing with np.square()
a18 = np.square(a16)
a18

array([[49., 49.,  4.,  0., 49.],
       [ 4.,  4.,  0., 16., 81.],
       [36., 81., 64., 36., 64.]])

In [102]:
# Find the mean of the latest array using np.mean()
np.mean(a18)

35.8

In [103]:
# Find the maximum of the latest array using np.max()
np.max(a18)

81.0

In [104]:
# Find the minimum of the latest array using np.min()
np.min(a18)

0.0

In [105]:
# Find the standard deviation of the latest array
np.std(a18)

28.505438077672128

In [106]:
# Find the variance of the latest array
np.var(a18)

812.5600000000001

In [108]:
# Reshape the latest array to (3, 5, 1)
a19 = np.reshape(a18, (3, 5, 1))
a19

array([[[49.],
        [49.],
        [ 4.],
        [ 0.],
        [49.]],

       [[ 4.],
        [ 4.],
        [ 0.],
        [16.],
        [81.]],

       [[36.],
        [81.],
        [64.],
        [36.],
        [64.]]])

In [109]:
# Transpose the latest array
a20 = a19.T
a20

array([[[49.,  4., 36.],
        [49.,  4., 81.],
        [ 4.,  0., 64.],
        [ 0., 16., 36.],
        [49., 81., 64.]]])

What does the transpose do?

In [110]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
a21 = np.random.randint(10, size=(3, 3))
a22 = np.random.randint(10, size=(3, 2))
a21, a22    

(array([[7, 1, 0],
        [6, 6, 7],
        [4, 2, 7]]),
 array([[5, 2],
        [0, 2],
        [4, 2]]))

In [111]:
# Perform a dot product on the two newest arrays you created
np.dot(a21, a22)

array([[35, 16],
       [58, 38],
       [48, 26]])

In [114]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
a23 = np.random.randint(10, size=(4, 3))
a24 = np.random.randint(10, size=(4, 3))
a23, a24

(array([[5, 3, 9],
        [6, 8, 6],
        [0, 0, 8],
        [8, 3, 8]]),
 array([[2, 6, 5],
        [7, 8, 4],
        [0, 2, 9],
        [7, 5, 7]]))

In [113]:
# Perform a dot product on the two newest arrays you created
np.dot(a23, a24)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [116]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
a25 = np.dot(a23, a24.T)
a25

array([[ 73,  95,  87, 113],
       [ 90, 130,  70, 124],
       [ 40,  32,  72,  56],
       [ 74, 112,  78, 127]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [4]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
a26 = np.random.randint(10, size=(3, 2))
a27 = np.random.randint(10, size=(3, 2))
a26, a27

(array([[7, 3],
        [4, 2],
        [9, 9]]),
 array([[7, 2],
        [2, 4],
        [8, 4]]))

In [119]:
# Compare the two arrays with '>'
a26 > a27

array([[ True, False],
       [False,  True],
       [False,  True]])

What happens when you compare the arrays with `>`?

In [120]:
# Compare the two arrays with '>='
a26 >= a27

array([[ True, False],
       [ True,  True],
       [False,  True]])

In [121]:
# Find which elements of the first array are greater than 7
a26 > 7

array([[False, False],
       [False, False],
       [False, False]])

In [122]:
# Which parts of each array are equal? (try using '==')
a26 == a27

array([[False, False],
       [ True, False],
       [False, False]])

In [123]:
# Sort one of the arrays you just created in ascending order
np.sort(a26)

array([[0, 7],
       [0, 1],
       [1, 5]])

In [125]:
a26

array([[7, 0],
       [0, 1],
       [1, 5]])

In [124]:
# Sort the indexes of one of the arrays you just created
np.argsort(a26)

array([[1, 0],
       [0, 1],
       [0, 1]], dtype=int64)

In [5]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(a26)

4

In [7]:
a26

array([[7, 3],
       [4, 2],
       [9, 9]])

In [6]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(a26)

3

In [10]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(a26, axis=1)

array([0, 0, 0], dtype=int64)

In [12]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(a26, axis=0)

array([1, 1], dtype=int64)

In [13]:
# Create an array of normally distributed random numbers
np.random.randn(3,5)

array([[ 0.10771744,  0.5031156 , -0.08929381, -0.08782228,  2.08139454],
       [ 0.82472249,  0.88687903,  1.33260767, -0.00700036, -0.96843796],
       [-0.74995592, -0.69884706, -2.05149558,  0.87592272, -0.1202925 ]])

In [15]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.